package bankidl;

/**
 * bankidl/Account.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * bank.idl den 25 oktober 2007 kl 20:51 CEST
 */
public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface Account
