package bankidl;

/**
 * bankidl/BankOperations.java . Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from bank.idl den 25 oktober 2007 kl 20:51 CEST
 */
public interface BankOperations {

    bankidl.Account newAccount(String name) throws bankidl.BankPackage.rejected;

    bankidl.Account getAccount(String name);

    boolean deleteAccount(String acc);
} // interface BankOperations
